name: Response Time CI
on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  response-time:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/response-time@v1.3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
